# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='nome',
            field=models.SlugField(allow_unicode=True, max_length=20),
        ),
    ]
